version: '3.3'
services:
  stock:
    image: jevans1441/stock-ticker:0.1.1
    env_file:
      - .env
    build: 
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports: 
      - 6060:80    
