version: '3.3'
services:
  stock:
    image: jevans1441/stock-ticker:0.1.2
    env_file:
      - .env
    build: 
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports: 
      - 80:80   
